# Generated by Django 4.0.2 on 2022-06-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumphoto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
